### ISSUE TITLE
Any non-trivial example using Rum?

### ISSUE THREAD

**Issue by aadrian** [tonsky/rum#29]
Hi,

Is there any non-trivial example using Rum?

thanks in advance.

**Comment by tonsky** [comment]
We’re using it at Cognician, but it’s closed source :( Maybe something will pop up soon, but it’s not there yet

**Comment by niwinz** [comment]
We are using it at uxbox/front (https://github.com/uxbox/uxbox).

(It's still work in progress)

**Comment by aadrian** [comment]
@niwinz Thank you for the link. Any link/document explaining it?

@tonsky  Any news on this? I think it's essential for the adoption of a framework to have as many usage examples as possible.

**Comment by niwinz** [comment]
@aadrian At this moment we dont have any documentation, but I have plans for the future publish a blog post about the architecture.

Using rum is really big win! In fact it can't be considered framework. We are using rum as lightweight clojure friendly api for react. It provides all the flexibility that we need. 

Personally I don't worry about the adoption. Its code base is small (400 LOC) and is easy to maintain.

**Comment by aadrian** [comment]
@niwinz Thanks for the details. A blog post would be helpful :).

**Comment by ghost** [comment]
FTR there is [a file](https://github.com/tonsky/rum/blob/gh-pages/examples/rum/examples.cljs) with plenty of examples in the rum repository which covers most of what rum provides: static, reactive, cursored, and stateful components. I also recommend learning about the React component model since rum is such a thin layer on top of it, but changing the lifecycle method signatures to be more functional.

**Comment by oakmac** [comment]
@aadrian - I used Rum to write [TourneyBot](https://github.com/oakmac/tourney-bot).

It's an open source web application to run ultimate frisbee tournaments.

**Comment by roman01la** [comment]
Closing this. There's a whole list in the README https://github.com/tonsky/rum#whos-using-rum
