### ISSUE TITLE
Missing symbols when fast typing in IE (Internet Explorer)

### ISSUE THREAD

**Issue by ai212983** [tonsky/rum#86]
Reproduced on IE11, Win8.

http://tonsky.me/rum/ - when fast typing in input field (like "Color"), some symbols will be missing. There's no such problem with [pure react form](http://ruanyf.github.io/react-demos/demo09/). Replacing `:value` with `:defaultValue` fixes the problem, so it seems the problem is with controlled inputs only.

**Comment by tonsky** [comment]
I debugged this problem once. If I remember correctly, it was caused by
reordering of keydown and keypress events (or something like that) that
only happens in IE. That time I switched to use of :default-value too. I’ll
look if it can be solved in more reliable way

**Comment by ai212983** [comment]
@tonsky Weird enough, pure react components work okay. Maybe they're handling this as special case, but I doubt it.

**Comment by tonsky** [comment]
This is because Rum (same as Om, Reagent and Quiscent) has batched
rendering on requestAnimationFrame, but doesn’t play well with inputs (you
can’t change value of input later, you have to do it in the onkeydown
handler). That’s why sablono wraps inputs to work around that problem
https://github.com/r0man/sablono/blob/master/src/sablono/interpreter.cljc#L14-L48.
Unfortunately, that causes typing issues in IE. Maybe something can be done
about it, it requires further investigation

**Comment by ai212983** [comment]
@tonsky I've created identical ticket for Reagent (as they experience the same problem), it seems they've fixed it: https://github.com/reagent-project/reagent/issues/253

**Comment by tonsky** [comment]
Just pushed 0.10.5 with sablono 0.7.3 that fixed that problem
